spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_account
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

    druid:
      filter: stat,wall
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: admin
        reset-enable: false

      web-stat-filter:
        enabled: false
        url-pattern:  /*
        exclusions:  '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'


  jdbc:
    template:
      query-timeout: 3
    #配置Mybatis规则
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:    #指定mybatis全局配置文件中的相关配置项
    map-underscore-to-camel-case: true
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true



